import "./globals.css";
import { Ovo, Roboto } from "next/font/google"
import { Header } from "./components/Header";
import { Navbar } from "./components/Navbar";
import { Footer } from "./components/Footer";
import { ShopContextProvider } from "./context/ShopContext";
import { ToastContainer } from "react-toastify";
import { GoogleAnalytics } from "@next/third-parties/google";
import 'react-toastify/dist/ReactToastify.css';



const ovo = Ovo({subsets: ["latin"], weight: ["400"], variable: "--font-ovo"});
const roboto = Roboto({subsets: ["latin"], weight: ["100", "300", "400", "500"], variable: "--font-roboto"});


// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };


export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <ShopContextProvider>
        <body className={`${roboto.variable} ${ovo.variable}`}>
          <Header />
          <Navbar />
            {children}
          <Footer />
          <ToastContainer
            position="top-center"
            autoClose={2500}
            hideProgressBar={true}
            closeOnClick={false}
          />
        </body>
      </ShopContextProvider>
      <GoogleAnalytics gaId="G-Q83VX4272W" />
    </html>
  );
}
