import { Ovo, Roboto } from "next/font/google"
import "./globals.css";
import { Header } from "./components/Header";
import { Navbar } from "./components/Navbar";
import { Footer } from "./components/Footer";


const ovo = Ovo({subsets: ["latin"], weight: ["400"], variable: "--font-ovo"});
const roboto = Roboto({subsets: ["latin"], weight: ["100", "300", "400", "500"], variable: "--font-roboto"});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${ovo.variable}`}>
        <Header />
        <Navbar />
          {children}
        <Footer />
      </body>
    </html>
  );
}
